# name: Unit Test

# on:
#   workflow_run:
#     workflows: ["flake8-lint"]
#     types:
#       - completed

# jobs:
#   test:
#     name: Unit Test
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out repo
#         uses: actions/checkout@v4

#       - name: Setup Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.13"
#           cache: "pip"

#       - name: Update pip
#         run: python -m pip install --upgrade pip

#       - name: Install App Requriements
#         run: pip install

name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_run:
    workflows: ["flake8-lint"]
    types:
      - completed

jobs:
  install-and-test:
    name: Install Dependencies and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          pip install -r requirements.txt  # Install the dependencies from requirements.txt

      - name: Run Tests
        run: |
          pytest
